sudo: required

language: php

services:
  - docker

install:
  - echo "install nothing"

script:
  - echo "no test"

after_success:
  - docker build -t louisliu/x265:latest ./x265
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
  - docker push louisliu/x265:latest
